name: Build CLI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
       # Check out code
      - name: Checkout
        uses: actions/checkout@v2

      # Setup go 1.17
      - name: Setup Go 1.17
        uses: actions/setup-go@v3.4.0
        with:
          go-version: '^1.17.0'

      # Set up Go pkg cache
      - name: Cache Go Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-cli-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-cli-go-

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      # Download go modules first
      - name: Download Go Modules
        run: go mod download

      # Build release binaries
      - name: Build CLI Release
        run: make dist-ginvoicer

      # Publish artifacts
      # https://github.com/softprops/action-gh-release/issues/142
      - name: Publish Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: |
            dist/*