name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    # Check out code
    - name: Checkout
      uses: actions/checkout@v2

    # Setup go 1.17
    - name: Setup Go 1.17
      uses: actions/setup-go@v3.2.1
      with:
        go-version: '^1.17.0'

    # Set up Go pkg cache
    - name: Cache Go Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Run linting
    - name: Run Lint
      run: make lint

    # Run unit tests
    # No tests yet :(
    # - name: Run Unit Tests
    #   run: make test
